#!/usr/bin/env node
"use strict";

var server;
var app;
var http;
var port;
var debug;

module.exports = class {
    constructor(chosenPort) {
        /**
         * Module dependencies.
         */

        app = require('./app');
        debug = require('debug')('express4:server');
        http = require('http');

        /**
         * Get port from environment and store in Express.
         */

        port = normalizePort(chosenPort || '3000');
        app.set('port', this.port);
        

        /**
         * Create HTTP server.
         */

        server = http.createServer(app);

        /**
         * Listen on provided port, on all network interfaces.
         */

        server.listen(port);
        server.on('error', onError);
        server.on('listening', onListening);

        /**
         * Event listener for HTTP server "listening" event.
         */

    }

    setModuleList(moduleList) {
        app.setModuleList(moduleList);
    }
};
/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
      ? 'Pipe ' + port
      : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

function onListening() {
    var addr = server.address();
    var bind = typeof addr === 'string'
        ? 'pipe ' + addr
        : 'port ' + addr.port;
    debug('Listening on ' + bind);
}