name: EsLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint
