name: EsLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update npm
      run: npm install -g npm
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint
